import './globals.css'
import { Nunito } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import RegisterModal from './components/modals/RegisterModal'
import ClientsOnly from './components/ClientsOnly'
import ToasterProvider from './providers/ToasterProvider'

export const metadata = {
  title: 'VBnB',
  description: 'Generated by create next app',
}

const font = Nunito({
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientsOnly>
          <ToasterProvider />
          <RegisterModal />
          <Navbar />
        </ClientsOnly>
        {children}
      </body>
    </html>
  )
}
